### ISSUE TITLE
suspension doesn't work

### ISSUE THREAD

**Issue by TermOfficial** [the-real-sumsome/witter#2]
I had tried fixing this issue with my own instance, but all I got was some random error like "unexpected }" even though the code clearly shows I put a if.
This should be fixed!

**Comment by TermOfficial** [comment]
Nevermind, I have some code to fix it.
$stmt = $conn->prepare("SELECT banstatus FROM `users` WHERE username = ?");
$stmt->bind_param("s", $username);
$stmt->execute();
$result = $stmt->get_result();
$row = $result->fetch_assoc();
$_SESSION['banstatus'] = $row['banstatus'];
if($_SESSION['banstatus'] == 'suspended'){ $error = "you're suspended"; }

**Comment by ezist** [comment]
Could you make this into a pull request, since you already have a fix?
